name: 'Login en Docker'
description: 'Login'
inputs:
  docker_username:  
    required: true
  registry_password: 
    required: true

runs: 
  using: "composite"
  steps:
    - name: Login to Registry
      run: |
        echo "${{ inputs.registry_password }}" | docker login -u "${{ inputs.docker_username }}" --password-stdin
