name: Main Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run_ci:
    if: github.event_name == 'push' &&  github.ref != 'refs/heads/dev'
    uses: ./.github/workflows/workflow-ci.yml
    secrets: inherit

  run_cd_dev:
    if: github.event_name == 'push' &&  github.ref == 'refs/heads/dev'
    name: CD - Dev Environment
    runs-on: ${{ matrix.os }}
    environment: dev
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run CD for Dev Environment
        uses: ./.github/workflows/workflow-cd.yml
        with:
          environment: dev
   

  run_cd_prod:
    if: github.event_name == 'push' &&  github.ref == 'refs/heads/main'
    name: CD - Prod Environment
    runs-on: ${{ matrix.os }}
    environment: prod
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run CD for Prod Environment
        uses: ./.github/workflows/workflow-cd.yml
        with:
          environment: prod
        

      