name: Main Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run_ci:
    uses: ./.github/workflows/workflow-ci.yml
    secrets: inherit

      