name: Reusable Container Workflow

on:
  push:
    branches:
      - palonso

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
        # Este comando inicia sesión en Docker Hub utilizando los secretos REGISTRY_USERNAME y REGISTRY_PASSWORD.

      - name: Set Image Tag
        run: |
          IMAGE_TAG="${{ github.sha }}"
          echo "Image tag set to: $IMAGE_TAG"
          sed -i "s/<IMAGE_TAG>/$IMAGE_TAG/g" Dockerfile 
        # Este comando establece la etiqueta de la imagen como el hash de confirmación actual de GitHub.
        #buscando todas las ocurrencias de image tag en el dockerfile
        #cada vez que se cree una nueva imagen tendrá una etiqueta unica asociada al hash del commit

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}

