name: Reusable Container Workflow

on:
  workflow_dispatch:
    inputs:
      execute-manually:
        description: 'Ejecutar manualmente el flujo de trabajo'
        required: true
        default: 'true'
  push:
    branches:
      - main
      - dev

jobs:
  set_image_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.set_image_tag.outputs.version}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Image Tag
        id: set_image_tag
        run: | 
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT

  build_and_push:
  # Es necesario añadir 'needs' del job del que queremos sacar las variables outputs 
    needs: set_image_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Registry
        uses: ./.github/actions/login-Registry
        with:
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set Image Tag
        run: |
          echo "Image tag set to: ${{ needs.set_image_tag.outputs.tag }}"

      - name: Build and push image
        uses: ./.github/actions/build-and-push-image
        with:
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          image_tag: ${{ needs.set_image_tag.outputs.tag }}