name: Reusable Container Workflow

on:
  workflow_dispatch:
    inputs:
      execute-manually:
        description: 'Ejecutar manualmente el flujo de trabajo'
        required: true
        default: 'true'
  push:
    branches:
      - main
      - dev

jobs:
    # runs-on: ubuntu-latest
    # outputs:
    #   tag: ${{steps.set_image_tag.outputs.version}}
    # steps:
    #   - name: image-tag
    #     uses: ./.github/actions/set-Image-Tag
    #   - name: Checkout Repository
    #     uses: actions/checkout@v2
    #   - name: Extraer valor de la version
    #     id: set_image_tag
    #     run: |
    #       echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
    #       echo $GITHUB_OUTPUT

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Registry
        uses: ./.github/actions/login-Registry
        with:
          docker_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Image-tag
        uses: ./.github/actions/set-Image-Tag

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app:${{ needs.set_image_tag.outputs.tag }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/app:${{ needs.set_image_tag.outputs.tag }}
