name: workflow cd
 
on:
  workflow_dispatch:
    inputs:
      execute-manually:
        description: 'Ejecutar manualmente el flujo de trabajo'
        required: true
        default: 'true'
 
  push:
    branches:
      - main
      - dev
 
jobs:
  get_image:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Set Image Tag Action
        uses: ./.github/actions/get-image-tag
        id: get_tag

  deploy:
    runs-on: ubuntu-latest
    needs: get_image

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull and Run Docker Image
      uses: ./.github/actions/pull-and-run-image
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        image_tag: ${{ needs.get_image.outputs.tag }}

    - name: Curl Tests
      uses: ./.github/actions/curl-tests